app:
  jwt:
    secret: ${JWT_SECRET:change-this-secret-key-change-this-secret-key}
    expiration-ms: 86400000

spring:
  application:
    name: habit-tracker-api

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  flyway:
    enabled: false

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /v3/api-docs
